// <auto-generated />
using ClinicFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ClinicFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClinicFlowDbContext))]
    [Migration("20260730212000_CreateClinicalRecords")]
    partial class CreateClinicalRecords
    {
    }
}
